const games = [
    "Mario Bros.",
    "Legend of Zelda",
    "Pokemon",
    "Warcraft",
    "The Elder Scrolls",
    "Fallout",
    "Doom",
    "Kingdom Hearts",
    "Crash Bandicoot",
    "Donkey Kong",
    "Tekken",
    "Borderlands",
    "The Sims",
    "Dead Space",
    "Animal Crossing",
    "Fable",
    "Contra",
    "Team Fortress",
    "Punch-Out",
    "Saints Row",
    "Jak and Daxter",
    "Guilty Gear",
    "Starcraft",
    "Nier",
    "Warhammer",
    "Final Fantasy",
    "Pikmin",
    "Tales of.",
    "Of Mana",
    "Metal Gear",
    "God of War",
    "Tetris",
    "Red Dead",
    "Street Fighter",
    "Chrono",
    "Ratchet and Clank",
    "Call of Duty",
    "Ages of Empires",
    "Need for Speed",
    "Harverst Moon",
    "Prince of Persia",
    "Max Payne",
    "Ninja Gaiden",
    "Persona",
    "Bayonetta",
    "Medal of Honor",
    "Dead or Alive",
    "Deux Ex",
    "Drakengard",
    "Breath of Fire",
    "Dragon Quest",
    "Halo",
    "GTA",
    "Diablo",
    "Assassin's Creed",
    "Metroid",
    "Bioshock",
    "Mass Effect",
    "StarFox",
    "The Last of Us",
    "Fire Emblem",
    "Far Cry",
    "Resident Evil",
    "Tony Hawk Pro Staker",
    "Grand Turismo",
    "Rayman",
    "Castlevania",
    "Soul Calibur",
    "Shin Megami Tensei",
    "Yakuza",
    "Command and Conquer",
    "SaGa",
    "Total War",
    "Phantasy Star",
    "Parasite Eve",
    "Mortal Kombat",
    "Megaman",
    "Uncharted",
    "Tomb Raider",
    "Portal",
    "Sonic the Hedgehog",
    "The Witcher",
    "Half-Life",
    "Spyro the Dragon",
    "Dark Souls",
    "Devil May Cry",
    "Silent Hill",
    "Hitman",
    "Dragon Age",
    "Gears of War",
    "Banjo-Kazooie",
    "Counter Strike",
    "Worms",
    "Shadow Hearts",
    "Bomberman",
    "Monster Hunter",
    "Shenmue",
    "Watch Dogs",
    "Dishonored",
    "Wild Arms"
];